services:
# ------------- KAFKA - MESSAGE BROKER ------------- #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    networks:
      - lapor-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - lapor-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - lapor-network

# ------------- FRONTEND ------------- #

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://103.197.188.83
    ports:
      - "30:3000" # Akses web di port 80 (atau 3000)
    restart: always
    container_name: frontend
    networks:
      - lapor-network
    
  iam-db:
    image: postgres:16
    container_name: iam-db
    environment:
      - POSTGRES_DB=iam_db
      - POSTGRES_USER=admin_iam
      - POSTGRES_PASSWORD=password_iam
    volumes:
      - iam_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin_iam", "-d", "iam_db"]
      interval: 5s
    networks:
      - lapor-network

  auth-service:
    build: ./authentication-service
    container_name: auth-service
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin_iam:password_iam@iam-db:5432/iam_db
      - SECRET_KEY=5400bcc59d07b2923ae210d8c85873eb4cce1fc17dfdec946f900394bec13102
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    ports:
      - "8003:8000"
    depends_on:
      iam-db:
        condition: service_healthy
    networks:
      - lapor-network

# ------------- REPORTING SERVICE ------------- #
  reporting-engine:
    build: ./reporting-engine
    container_name: reporting-engine
    restart: always
    ports:
      - "8001:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - GOOGLE_DRIVE_FOLDER_ID=1klLGJGkgWKLnK79JoSaXgqWwuPtMYSJV
      - GOOGLE_CLIENT_ID=478710131700-d7aogvhn7fgodr3i8j3hdlsvs7u4u7ld.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REFRESH_TOKEN=1//0gBUiGL_WjSyECgYIARAAGBASNwF-L9IrsZaDFlOVoH1yKD1rlhUef-zL0Lcc45yRVp576tyaHtJPQP8jG1ED-2vfMD-zABuQgWQ
    depends_on:
      - kafka
    volumes:
      - ./reporting-engine/service-account.json:/app/service-account.json:ro
    networks:
      - lapor-network

  report-db:
    image: postgres:16
    container_name: report-db
    environment:
      - POSTGRES_DB=report_db
      - POSTGRES_USER=admin_report
      - POSTGRES_PASSWORD=password_report
    volumes:
      - report_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin_report", "-d", "report_db"]
      interval: 5s
    networks:
      - lapor-network

  report-service:
    build: ./report-service
    container_name: report-service
    ports:
      - "8004:8000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin_report:password_report@report-db:5432/report_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SECRET_KEY=5400bcc59d07b2923ae210d8c85873eb4cce1fc17dfdec946f900394bec13102

    depends_on:
      report-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - lapor-network

# ------------- NOTIFICATION SERVICE ------------- #
  notification_service:
      build: ./notification_service 
      container_name: notification_service
      restart: always
      depends_on:
        notif-postgres:
          condition: service_healthy 
        kafka:
          condition: service_started
      environment:
        - DATABASE_URL=postgresql://notif:notif@notif-postgres:5432/notif
        - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
        - KAFKA_TOPIC=notifications
      ports:
        - "8002:8000" # Port API Notif
      networks:
        - lapor-network

  notif-postgres:
      image: postgres:16
      container_name: notif-postgres
      environment:
        POSTGRES_DB: notif
        POSTGRES_USER: notif
        POSTGRES_PASSWORD: notif
      ports:
        - "5438:5432"
      volumes:
        - notif_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "notif"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - lapor-network

# ------------- VOLUMES ------------- #
volumes:
  notif_data:
  kafka_data:
  zookeeper_data:
  report_data:
  iam_data:
  
networks:
  lapor-network:
    driver: bridge