services:
# ------------- KAFKA - MESSAGE BROKER ------------- #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka

# ------------- REPORTING SERVICE ------------- #
  reporting-engine:
    build: ./reporting-engine
    container_name: reporting-engine
    restart: always
    ports:
      - "8001:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - GOOGLE_DRIVE_FOLDER_ID=1klLGJGkgWKLnK79JoSaXgqWwuPtMYSJV
    depends_on:
      - kafka
    volumes:
      - ./reporting-engine/service-account.json:/app/service-account.json:ro

  report-db:
    image: postgres:16
    container_name: report-db
    environment:
      - POSTGRES_DB=report_db
      - POSTGRES_USER=admin_report
      - POSTGRES_PASSWORD=password_report
    volumes:
      - report_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin_report", "-d", "report_db"]
      interval: 5s

  report-service:
    build: ./report-service
    container_name: report-service
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin_report:password_report@report-db:5432/report_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      report-db:
        condition: service_healthy
      kafka:
        condition: service_started

# ------------- NOTIFICATION SERVICE ------------- #
  notification_service:
      build: ./notification_service 
      container_name: notification_service
      restart: always
      depends_on:
        notif-postgres:
          condition: service_healthy 
        kafka:
          condition: service_started
      environment:
        - DATABASE_URL=postgresql://notif:notif@notif-postgres:5432/notif
        - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
        - KAFKA_TOPIC=notifications
      ports:
        - "8002:8000" # Port API Notif
        
  notif-postgres:
      image: postgres:16
      container_name: notif-postgres
      environment:
        POSTGRES_DB: notif
        POSTGRES_USER: notif
        POSTGRES_PASSWORD: notif
      ports:
        - "5438:5432"
      volumes:
        - notif_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "notif"]
        interval: 10s
        timeout: 5s
        retries: 5


# ------------- VOLUMES ------------- #
volumes:
  notif_data:
  kafka_data:
  zookeeper_data:
  report_data:
  
