version: '3.8'


services:
  # db:
  #   image: postgres:15
  #   container_name: db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - microservice-net

  web:
    build: .
    container_name: auth-service
    # depends_on:
    #   - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - microservice-net

volumes:
  pgdata:

networks:
  microservice-net:
    external: true